version: "3.3"

services:
  bootstrap:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ./.docker/bootstrap.sh

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - bootstrap
    ports:
      - "8000:3000"

  mongo:
    image: mongo:4.2.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: docker
