openapi: "3.0.2"
info:
  description: "A Node.js authentication API that uses JWT to provide very simple endpoints, and straightforward user authentication. \n\n This project has a basic behavior and it's intended to be the backbone of more complex user management."
  version: "1.0.0"
  title: "Auth API"
  license:
    name: "MIT"
    url: "https://github.com/iammateus/AuthAPI/blob/master/LICENSE"
servers:
  - url: http://localhost:8000
    description: Local server
tags:
- name: "User"
  description: "Operations about user"
paths:
  /users:
    post:
      tags:
      - "User"
      summary: "Create user"
      operationId: "createUser"
      requestBody:
        description: "User data"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userInput"
      responses:
        201:
          description: "Success"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: "string"
                    example: "The user was created successfully"
        422:
          description: "Invalid data"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: "string"
                    example: '"email" is required'
  /users/me:
    get:
      security:
        - auth: [] 
      tags:
      - "User"
      summary: "Show user"
      operationId: "showUser"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema: 
                type: object
                description: "User data"
        401:
          description: "Unauthorized"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: "string"
                    example: "Unauthorized"
components:
  schemas:
    userInput:
      type: "object"
      properties:
        email:
          type: "string"
          example: "user@email.com"
          description: "Should be a valid email"
        name:
          type: "string"
          example: "Funny Puppy"
        password:
          type: "string"
          example: "&8mTwX*e"
          description: "Should have at least 8 characters"
        password_confirmation:
          type: "string"
          example: "&8mTwX*e"
          description: "Should have the same value of the field \"password\""
      required:
        - "email"
        - "name"
        - "password"
        - "password_confirmation"
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
